### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by jamesturk** [bashu/django-secretballot#60]
It has been years since I've had any need for this project, and I'd love to hand it over to someone that cares about it and wants to maintain it.  If you're seeing this get in touch and I'd be glad to transfer.  I have no plans to release any versions after 1.0.0 right now.

**Comment by bashu** [comment]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

**Comment by bashu** [comment]
We still use it some legacy projects and I am willing to keep it maintained. If you are not sure about me, for example I maintain (or helping to maintain):

https://github.com/shanx/django-maintenancemode

https://github.com/adamcharnock/django-tz-detect

Also I adopted few Django projects and still continue maintaining them, biggest example:

https://github.com/bashu/django-easy-maps

**Comment by jamesturk** [comment]
thanks for getting in touch, I'd be glad to send it your way
